services:
  db:
    image: postgres:16
    container_name: meip-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: meip_db
      POSTGRES_USER: meip_admin
      POSTGRES_PASSWORD: meippass123
    ports:
      - "5432:5432"
    volumes:
      - meip_postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

volumes:
  meip_postgres_data:
