import {verificationFields,evidenceFields,mappingFields,impactFields,metricFields,horizonFields,advancedFields,type Fields} from './fields';

type Help = readonly [meaning:string, example:string];
export type GuideSection = {title:string; fields:Fields; help:Record<string,Help>};
const section = (title:string,fields:Fields,help:Record<string,Help>):GuideSection => ({title,fields,help});
export const reviewGuide: GuideSection[][] = [
 [section('Verify news',verificationFields,{
 headline:['A factual headline you have checked against the source.','Producer announces a 5% output cut.'],
 summary:['What happened, who is involved and why it matters.','Output falls next month after scheduled maintenance.'],
 acceptance_reason:['Why this article belongs in the accepted news collection.','Official announcement with a material supply change.'],
 category:['The event family used for classification and scoring; ma means mergers and acquisitions.','macro for an economy-wide supply shock.'],
 verification_status:['How well the central claim is supported; distinguish partial verification from a disputed claim.','confirmed after checking the official release.'],
 source_classification:['The kind of source behind the article.','Company filing, regulator notice or news report.'],
 source_credibility:['Optional 0–1 judgment of source reliability, not a probability.','0.9 for an attributable official filing.'],
 occurrence_certainty:['Whether the event time is exact, approximate or unknown.','approximate when only the month is known.'],
 occurrence_at:['When the event happened, entered in UTC; this is separate from publication time.','2026-09-28 09:00 UTC.'],
 novelty:['Whether this adds a new event, updates or corrects one, or repeats known information.','update when a proposed cut becomes confirmed.'],
 related_event_id:['Select the existing event that this update, correction or repetition relates to.','The earlier proposed output-cut event.'],
 concerns:['Unresolved source or factual limitations.','The size of the cut has not been independently confirmed.'],
 additional_evidence:['Extra corroboration or context for your verification.','A regulator notice confirms the shutdown dates.'],
 }),section('Related events',{event_ids:{label:'Additional existing events referenced by this article'}},{event_ids:['Select other existing events mentioned by this article.','An earlier outage and the subsequent reopening.']}),
 section('Supporting sources',evidenceFields,{
 label:['A short name that identifies this evidence.','Producer September operations update.'],
 url:['A direct HTTP or HTTPS link to the supporting source.','https://example.com/operations-update'],
 classification:['The type of this individual supporting source.','Official company announcement.'],
 excerpt:['A short relevant quotation, preserving the source wording.','“Production will decline by 5% in October.”'],
 document_ref:['Where to find the claim within a document.','Operations update, page 3, paragraph 2.'],
 })],
 [section('Entity mapping',mappingFields,{
 entity_id:['The existing canonical entity affected by the news; it need not have a ticker.','An airline affected by higher fuel costs.'],
 entity_type:['What the selected entity represents.','company for an airline; commodity for crude oil.'],
 security_id:['Optional listed security belonging to this entity.','The company’s ordinary shares on its exchange.'],
 relationship:['The entity’s role relative to the event.','customer for an airline buying fuel.'],
 exposure:['Whether the event affects this entity immediately or through intermediate effects.','indirect for an airline affected by an oil supply cut.'],
 transmission:['How the event reaches the entity economically.','Lower oil supply raises fuel costs and pressures margins.'],
 mapping_confidence:['A 0–1 heuristic for confidence in the entity connection, not a probability.','0.8 when fuel exposure is documented.'],
 mapping_reason:['Evidence supporting why this entity is linked to the event.','Annual report identifies fuel as a major expense.'],
 exposure_magnitude:['A qualitative description of the size of exposure.','High fuel-cost sensitivity.'],
 exposure_value:['Optional numeric size of exposure, with units in the next field.','30 when fuel represents 30% of operating costs.'],
 exposure_basis:['Units and the basis for the numeric exposure.','Percent of operating costs, latest annual report.'],
 }),section('Causal chain',{chain:{label:'Ordered causal chain'}},{chain:['Add each cause-and-effect step in order; required for indirect exposure.','Supply cut → higher oil price → higher airline fuel costs.']}),
 section('Create a canonical entity',{name:{label:'Canonical name'},ticker:{label:'Ticker (optional)'},entity_type:mappingFields.entity_type},{name:['The standard name for a new entity; check existing entities first.','Example Airlines Ltd.'],ticker:['Optional trading identifier; leave blank for entities without one.','EXAIR, or blank for a country.'],entity_type:['The kind of entity being created.','company for Example Airlines Ltd.']}),
 section('Add a security',{entity_id:mappingFields.entity_id,symbol:{label:'Security symbol'},exchange:{label:'Exchange'}},{entity_id:['The canonical entity that owns this security.','Example Airlines Ltd.'],symbol:['The trading symbol for this particular security.','EXAIR.'],exchange:['The exchange where the security trades.','NSE.']})],
 [section('Impact assessment',impactFields,{
 direction:['Whether the effect on this entity is favorable, adverse, mixed, neutral or unknown.','negative for an airline facing higher fuel costs.'],
 rationale:['Explain why the expected effect follows from the evidence.','Fuel costs rise before ticket prices can adjust.'],
 metrics_status:['Choose specified when you can name affected metrics; otherwise choose unknown.','specified with an operating-margin metric below.'],
 magnitude:['The expected size of the effect, separate from its positive or negative direction.','medium for a meaningful but manageable margin reduction.'],
 range_low:['Optional lower end of a quantified effect; state units and evidence.','-2 for a margin change of -2 to -1 percentage points.'],
 range_high:['Optional upper end of the same quantified effect.','-1 for that margin-change range.'],
 range_basis:['Units, baseline and support for the magnitude range.','Margin percentage points versus baseline, using fuel sensitivity.'],
 effect_type:['Whether the effect concerns business fundamentals, market sentiment or both.','fundamentals when operating costs change.'],
 impact_confidence:['A 0–1 heuristic for confidence in the impact assessment, not a probability.','0.6 when hedging coverage is uncertain.'],
 surprise:['How the event compares with documented expectations.','below when reported earnings miss consensus.'],
 expectations_evidence:['The source and baseline used for the expectations comparison.','Consensus expected EPS of 10; reported EPS was 8.'],
 anticipated:['Whether the information was previously known or expected.','yes if management announced the cut last month.'],
 anticipated_evidence:['Evidence for whether the event was anticipated.','Prior guidance already included the planned shutdown.'],
 assumptions:['Material conditions your analysis depends on; use none identified when appropriate.','Fuel prices stay elevated and hedges cover only half of demand.'],
 counterarguments:['Reasons the expected effect may be weaker or reversed.','Higher ticket prices could offset fuel costs.'],
 invalidation:['Observable conditions that would undermine the assessment.','Oil prices return to their pre-event level.'],
 quantitative_evidence:['Numbers and sources supporting the assessment.','Annual report: fuel was 30% of operating expenses.'],
 }),section('Affected metrics',metricFields,{
 name:['The business or financial measure affected.','Operating margin.'],
 change:['Whether the metric increases or decreases; this is separate from whether that is good or bad.','increase for fuel expense.'],
 implication:['Whether that metric change benefits or harms the business.','adverse for an increase in fuel expense.'],
 value_low:['A single value or lower bound; explain the comparison in the baseline field.','12 for an expected margin of 12–14%.'],
 value_high:['Optional upper bound of the same metric range.','14 for the 12–14% margin range.'],
 unit:['The measurement unit or currency.','%, percentage points or INR million.'],
 baseline:['The reference value or scenario used for comparison.','Prior-year operating margin of 15%.'],
 period:['The period the observed or expected metric covers.','October–December 2026.'],
 evidence_id:['Select the supporting source already added under verification.','The September operations update.'],
 }),section('Optional advanced analysis',advancedFields,{
 base:['The central scenario you consider most plausible.','Oil remains elevated for one quarter.'],
 upside:['A more favorable outcome for this entity.','Fuel prices normalize within a month.'],
 downside:['A less favorable outcome for this entity.','Supply disruptions persist for two quarters.'],
 scenario_assumptions:['Conditions distinguishing the scenarios.','Different outage duration and ticket-price recovery.'],
 base_likelihood:['Optional subjective weight from 0 to 1 for the base scenario.','0.6; keep the three scenario weights coherent.'],
 upside_likelihood:['Optional subjective weight from 0 to 1 for the upside scenario.','0.2 alongside base 0.6 and downside 0.2.'],
 downside_likelihood:['Optional subjective weight from 0 to 1 for the downside scenario.','0.2 alongside base 0.6 and upside 0.2.'],
 dependencies:['Other conditions needed for the assessment to hold.','No offsetting tax reduction or hedge payout.'],
 second_order:['Effects that arise after the initial impact.','Weaker demand after airlines raise fares.'],
 monitoring:['Indicators that would help confirm or challenge the analysis.','Jet fuel prices, load factors and fare changes.'],
 owner:['The person or team responsible for follow-up.','Transport research team.'],
 specialist:['Whether a specialist review is needed.','yes for complex regulatory interpretation.'],
 })],
 [section('Horizons and follow-up',horizonFields,{
 horizon:['The time window being assessed; add separate rows for different windows.','Choose the short-term window from the list.'],
 onset:['When you expect the effect to begin.','Next month, when fuel contracts reset.'],
 duration:['How long the effect is expected to last.','Approximately one quarter.'],
 direction:['The effect on this entity within this particular time window.','negative short term, neutral over a longer horizon.'],
 magnitude:['The size of the effect within this time window.','medium during the next quarter.'],
 confidence:['A 0–1 heuristic for this horizon assessment, not a probability.','0.5 because contract reset dates vary.'],
 timing_rationale:['Why the effect starts and lasts as estimated.','Existing hedges delay the cost increase by a month.'],
 persistence:['Whether the effect is one-off, temporary, recurring, structural or unknown.','temporary for a planned maintenance shutdown.'],
 catalyst:['The next development that could change the assessment.','The producer’s reopening announcement.'],
 catalyst_date:['The expected calendar date of that development, if known.','2026-10-15.'],
 date_certainty:['How firmly the catalyst date is known.','estimated when management gives an indicative date.'],
 review_date:['When the reviewer should revisit this assessment.','2026-10-16, after the expected announcement.'],
 })],
 [section('Acceptance outcomes',{pending:{label:'Accept — enrichment pending'},ready:{label:'Accept — analysis ready'}},{pending:['Accept verified news while entity links or analysis remain incomplete; ticker links are optional.','Accept a verified supply announcement and link affected entities later.'],ready:['Accept when verification and all required analysis sections are complete.','Accept with supported mappings, impacts and horizon assessments.']})],
];
