'use client';
import {useEffect,useId,useState} from 'react';
import Link from 'next/link';
import type {ReviewData,Draft} from '@/lib/reviews/api';
import {acceptanceErrors,validateDocument,fieldErrors,type ReviewDocument,type Values,type Mapping,type Outcome} from '@/lib/reviews/model';
import {verificationFields,evidenceFields,mappingFields,impactFields,metricFields,horizonFields,advancedFields,observationFields,type Fields} from '@/lib/reviews/fields';
import {scoreReviewAssessment} from '@/lib/scoring';
import ReviewSummary from '@/components/ReviewSummary';
import ReviewGuide from '@/components/ReviewGuide';
const box='rounded border border-[#30363d] bg-[#0d1117] px-3 py-2 w-full text-sm';
const button='rounded border border-[#30363d] px-3 py-2 text-sm disabled:opacity-40 hover:border-[#58a6ff]';
type Option={value:string;label:string};
function FieldsForm({spec,values,onChange,options={}}:{spec:Fields;values:Values;onChange:(v:Values)=>void;options?:Record<string,Option[]>}){
 const id=useId();return <div className="grid gap-4 md:grid-cols-2">{Object.entries(spec).map(([key,field])=>{const validation=fieldErrors({[key]:values[key]},{[key]:field},'').map(message=>message.replace(/^: /,''));const choices=options[key]??field.options?.map(value=>({value,label:value.replaceAll('_',' ')}));const change=(value:string)=>onChange({...values,[key]:field.kind==='number'?(value===''?null:Number(value)):value});return <label key={key} htmlFor={`${id}-${key}`} className={field.kind==='textarea'?'md:col-span-2':''}><span className="mb-1 block text-sm">{field.label}{field.required?' *':''}</span>{choices?<select id={`${id}-${key}`} aria-invalid={validation.length>0} aria-describedby={validation.length?`${id}-${key}-error`:undefined} className={box} value={values[key]??''} onChange={e=>change(e.target.value)}><option value="">Select / not entered</option>{choices.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:field.kind==='textarea'?<textarea id={`${id}-${key}`} aria-invalid={validation.length>0} aria-describedby={validation.length?`${id}-${key}-error`:undefined} className={box} rows={3} value={values[key]??''} onChange={e=>change(e.target.value)}/>:<input id={`${id}-${key}`} aria-invalid={validation.length>0} aria-describedby={validation.length?`${id}-${key}-error`:undefined} className={box} type={field.kind??'text'} step={field.kind==='number'?'any':undefined} min={field.min} max={field.max} value={values[key]??''} onChange={e=>change(e.target.value)}/>} {!!validation.length&&<small id={`${id}-${key}-error`} role="alert" className="block text-red-300">{validation.join('; ')}</small>}</label>})}</div>;
}
async function request<T>(action:string,args:unknown):Promise<T>{const r=await fetch('/api/news/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,args})});const data=await r.json();if(!r.ok)throw new Error(data.error??'Review operation failed');return data;}
function newMapping():Mapping{return {id:crypto.randomUUID(),fields:{},chain:[],impact:{direction:'unknown',magnitude:'unknown',metrics_status:'unknown',surprise:'unknown',anticipated:'unknown'},metrics:[],horizons:[],advanced:{}};}
export default function ReviewClient({articleKey,initial,initialDocument}:{articleKey:string;initial:ReviewData;initialDocument:ReviewDocument}){
 const [data,setData]=useState(initial),[doc,setDoc]=useState(initialDocument),[draft,setDraft]=useState<Draft|null>(initial.draft),[editing,setEditing]=useState(!!initial.draft||!initial.versions.length),[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [versionId,setVersionId]=useState(initial.versions[0]?.id??''),[observation,setObservation]=useState<Values>({mode:'carried_forward',outcome:'pending'}),[observationDirty,setObservationDirty]=useState(false),[entity,setEntity]=useState<Values>({entity_type:'company'}),[security,setSecurity]=useState<Values>({});
 const [guideOpen,setGuideOpen]=useState(false);
 const showGuide=editing&&data.canReview&&data.articleDecision!=='rejected';
 const modify=(next:ReviewDocument)=>{setDoc(next);setDirty(true);setMessage('');};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||observationDirty){e.preventDefault();e.returnValue='';}};const click=(e:MouseEvent)=>{if((dirty||observationDirty)&&(e.target as HTMLElement).closest('a[href]')&&!window.confirm('Leave without saving your draft or observation?')){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',warn);document.addEventListener('click',click,true);return()=>{window.removeEventListener('beforeunload',warn);document.removeEventListener('click',click,true);};},[dirty,observationDirty]);
 const refresh=async()=>{const r=await fetch(`/api/news/reviews?article=${encodeURIComponent(articleKey)}`,{cache:'no-store'});const next=await r.json();if(!r.ok)throw new Error(next.error??'Unable to refresh review');setData(next as ReviewData);return next as ReviewData;};
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Operation failed');}finally{setBusy(false);}};
 const save=async()=>{validateDocument(doc);const saved=await request<Draft>('save',{article:articleKey,draft_id:draft?.id,revision:draft?.revision,document:doc});setDraft(saved);setDirty(false);return saved;};
 const accept=(outcome:Outcome)=>perform(async()=>{validateDocument(doc);const errors=acceptanceErrors(doc,outcome);if(errors.length)throw new Error(errors.join('\n'));const saved=dirty||!draft?await save():draft;const result=await request<{version_id:string}>('accept',{draft_id:saved.id,revision:saved.revision,outcome});setDirty(false);setEditing(false);setDraft(null);setVersionId(result.version_id);await refresh();setMessage('Accepted as an immutable review version.');});
 const updateMapping=(i:number,next:Mapping)=>modify({...doc,mappings:doc.mappings.map((m,j)=>j===i?next:m)});
 const entityOptions=data.entities.map(e=>({value:e.id,label:`${e.name}${e.ticker?` (${e.ticker})`:''}`}));const eventOptions=data.events.map(e=>({value:e.id,label:e.title}));
 const pendingErrors=acceptanceErrors(doc,'accepted_pending_enrichment'),readyErrors=acceptanceErrors(doc,'accepted_analysis_ready');const selectedVersion=data.versions.find(v=>v.id===versionId)??data.versions[0];
 return <section className="mx-auto max-w-[1440px] space-y-5"><Link href="/app/news-ingestion" className="text-[#58a6ff]">← NewsIngestion</Link><h1 className="text-2xl font-semibold">Structured news review</h1>
 <p className="text-sm text-[#9aa7b4]">Published: {String(data.article.published_at??'unknown')} · Ingested: {String(data.article.fetched_at??'unknown')}. Occurrence and acceptance are recorded separately. * Required for the relevant acceptance outcome.</p>
 {error&&<p role="alert" className="whitespace-pre-wrap rounded border border-red-600 p-3 text-red-300">{error}</p>}{message&&<p role="status" className="text-green-400">{message}</p>}
 {!data.canReview&&<p role="status">Read-only access. An administrator must grant reviewer membership before you can save or accept.</p>}
 {data.articleDecision==='rejected'&&<p role="status">This article was rejected. Review history remains available.</p>}
 {editing&&data.articleDecision!=='rejected'&&<div className={showGuide?`grid items-start gap-5 ${guideOpen?'lg:grid-cols-[minmax(0,1fr)_17rem]':'lg:grid-cols-[minmax(0,1fr)_6rem]'}`:''}>
 <fieldset disabled={busy||!data.canReview} className="min-w-0 space-y-5">
 <nav aria-label="Review steps" className="flex flex-wrap gap-2">{['Verify news','Map entities','Assess impact','Horizons & follow-up','Preview & accept'].map((label,i)=><button key={label} className={button+(step===i?' border-blue-400':'')} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {label}</button>)}</nav>
 {!!data.versions.length&&<button className={button} onClick={()=>{if(window.confirm('Replace this editing session with the latest accepted version? The previous saved draft remains archived.'))void perform(async()=>{const next=await request<Draft>('restart',{article:articleKey});setDraft(next);setDoc(next.document);setDirty(false);await refresh();setMessage('New draft created from the latest accepted version.');});}}>Start a fresh draft from latest accepted version</button>}
 <p className="text-sm">Draft {dirty?'has unsaved changes':draft?`saved (revision ${draft.revision})`:'not yet saved'} · Verification: {pendingErrors.length?`${pendingErrors.length} requirements missing`:'complete'} · Analysis: {readyErrors.length?`${readyErrors.length} requirements missing`:'complete'}</p>
 {step===0&&<div className="space-y-5"><FieldsForm spec={verificationFields} values={doc.verification} onChange={verification=>modify({...doc,verification})} options={{related_event_id:eventOptions}}/>
 <label className="block">Additional existing events referenced by this article<select multiple className={box} value={doc.event_ids} onChange={e=>modify({...doc,event_ids:Array.from(e.target.selectedOptions,o=>o.value)})}>{eventOptions.map(e=><option key={e.value} value={e.value}>{e.label}</option>)}</select></label>
 <h2 className="text-lg">Supporting sources</h2>{doc.evidence.map((e,i)=><div className="space-y-3 rounded border border-[#30363d] p-4" key={e.id}><h3>Evidence {i+1}</h3><FieldsForm spec={evidenceFields} values={e.fields} onChange={fields=>modify({...doc,evidence:doc.evidence.map((row,j)=>j===i?{...row,fields}:row)})}/><button className={button} onClick={()=>modify({...doc,evidence:doc.evidence.filter((_,j)=>j!==i)})}>Remove evidence {i+1}</button></div>)}<button className={button} onClick={()=>modify({...doc,evidence:[...doc.evidence,{id:crypto.randomUUID(),added_at:new Date().toISOString(),fields:{}}]})}>Add source reference</button></div>}
 {step===1&&<div className="space-y-4"><p>Mapping may remain pending when accepting for enrichment. Use canonical entities; tickers are optional.</p>{doc.mappings.map((m,i)=><div className="rounded border border-[#30363d] p-4 space-y-4" key={m.id}><h2>Entity mapping {i+1}</h2><FieldsForm spec={mappingFields} values={m.fields} onChange={fields=>{if(fields.entity_id!==m.fields.entity_id){fields.entity_type=data.entities.find(e=>e.id===fields.entity_id)?.entity_type??'';fields.security_id='';}updateMapping(i,{...m,fields});}} options={{entity_id:entityOptions,security_id:data.securities.filter(s=>s.entity_id===m.fields.entity_id).map(s=>({value:s.id,label:`${s.symbol} ${s.exchange??''}`}))}}/>
 <h3>Ordered causal chain {m.fields.exposure==='indirect'?'*':''}</h3>{m.chain.map((s,j)=><label className="flex gap-2" key={j}><span>Step {j+1}</span><input className={box} value={s} onChange={e=>updateMapping(i,{...m,chain:m.chain.map((x,k)=>k===j?e.target.value:x)})}/><button className={button} aria-label={`Remove causal step ${j+1}`} onClick={()=>updateMapping(i,{...m,chain:m.chain.filter((_,k)=>k!==j)})}>Remove</button></label>)}<button className={button} onClick={()=>updateMapping(i,{...m,chain:[...m.chain,'']})}>Add causal step</button><button className={button} onClick={()=>modify({...doc,mappings:doc.mappings.filter((_,j)=>j!==i)})}>Remove mapping</button></div>)}<button className={button} onClick={()=>modify({...doc,mappings:[...doc.mappings,newMapping()]})}>Add affected entity</button>
 <details><summary>Create a canonical entity</summary><FieldsForm spec={{name:{label:'Canonical name',required:true},ticker:{label:'Ticker (optional)'},entity_type:mappingFields.entity_type}} values={entity} onChange={setEntity}/><button className={button} onClick={()=>perform(async()=>{await request('entity',entity);await refresh();setEntity({entity_type:'company'});setMessage('Entity created. Select it in a mapping.');})}>Create entity</button></details>
 <details><summary>Add a security to an entity</summary><FieldsForm spec={{entity_id:mappingFields.entity_id,symbol:{label:'Security symbol',required:true},exchange:{label:'Exchange'}}} values={security} onChange={setSecurity} options={{entity_id:entityOptions}}/><button className={button} onClick={()=>perform(async()=>{await request('security',security);await refresh();setSecurity({});setMessage('Security created.');})}>Create security</button></details></div>}
 {step===2&&<div className="space-y-6">{!doc.mappings.length&&<p>Add an entity mapping, or accept with enrichment pending.</p>}{doc.mappings.map((m,i)=><section className="space-y-4 rounded border border-[#30363d] p-4" key={m.id}><h2>{data.entities.find(e=>e.id===m.fields.entity_id)?.name??`Entity ${i+1}`}</h2><FieldsForm spec={impactFields} values={m.impact} onChange={impact=>updateMapping(i,{...m,impact})}/><p>Metric change and business implication are independent: a cost increase can be adverse.</p>{m.metrics.map((metric,j)=><div className="space-y-2 border-t border-[#30363d] pt-3" key={j}><FieldsForm spec={metricFields} values={metric} onChange={values=>updateMapping(i,{...m,metrics:m.metrics.map((x,k)=>k===j?values:x)})} options={{evidence_id:doc.evidence.map(e=>({value:e.id,label:String(e.fields.label??'Untitled evidence')}))}}/><button className={button} onClick={()=>updateMapping(i,{...m,metrics:m.metrics.filter((_,k)=>k!==j)})}>Remove metric {j+1}</button></div>)}<button className={button} onClick={()=>updateMapping(i,{...m,impact:{...m.impact,metrics_status:'specified'},metrics:[...m.metrics,{}]})}>Add metric</button><details><summary>Optional scenarios and advanced analysis</summary><FieldsForm spec={advancedFields} values={m.advanced} onChange={advanced=>updateMapping(i,{...m,advanced})}/></details></section>)}</div>}
 {step===3&&<div className="space-y-5"><p>Horizon ranges are analysis conventions, not promises. Dates are entered explicitly; no trading-day calendar arithmetic is applied.</p>{!doc.mappings.length&&<p>Map an entity to add horizon assessments.</p>}{doc.mappings.map((m,i)=><div key={m.id} className="space-y-3 rounded border border-[#30363d] p-4"><h2>{data.entities.find(e=>e.id===m.fields.entity_id)?.name??`Entity ${i+1}`}</h2>{m.horizons.map((h,j)=><div key={j} className="space-y-2 border-t border-[#30363d] pt-3"><FieldsForm spec={horizonFields} values={h} onChange={values=>updateMapping(i,{...m,horizons:m.horizons.map((x,k)=>k===j?values:x)})} options={{horizon:data.horizons.map(h=>({value:h.key,label:h.label}))}}/><button className={button} onClick={()=>updateMapping(i,{...m,horizons:m.horizons.filter((_,k)=>k!==j)})}>Remove horizon {j+1}</button></div>)}<button className={button} onClick={()=>updateMapping(i,{...m,horizons:[...m.horizons,{direction:'unknown',magnitude:'unknown',persistence:'unknown',date_certainty:'unknown'}]})}>Add horizon assessment</button></div>)}</div>}
 {step===4&&<div className="space-y-4"><ReviewSummary document={doc} entities={Object.fromEntries(data.entities.map(e=>[e.id,e.name]))}/><h2>Rules-derived preview (server recalculates on acceptance)</h2>{doc.mappings.map(m=>{const score=scoreReviewAssessment({category:doc.verification.category,direction:m.impact.direction??'unknown',magnitude:m.impact.magnitude??'unknown',sourceCredibility:doc.verification.source_credibility??null,mappingConfidence:m.fields.mapping_confidence??null,impactConfidence:m.impact.impact_confidence??null});return <p key={m.id}>{data.entities.find(e=>e.id===m.fields.entity_id)?.name??'Unmapped'}: {score.status} · magnitude {score.magnitude??'unknown'} · {score.rationale}</p>;})}<details open><summary>Missing acceptance requirements</summary><p>Enrichment pending:</p>{pendingErrors.length?<ul className="list-disc pl-6">{pendingErrors.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>Verification complete.</p>}<p>Analysis ready:</p>{readyErrors.length?<ul className="list-disc pl-6">{readyErrors.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>All required sections complete.</p>}</details><div className="flex flex-wrap gap-3"><button className={button} disabled={pendingErrors.length>0} onClick={()=>accept('accepted_pending_enrichment')}>Accept — enrichment pending</button><button className={button+' bg-[#238636]'} disabled={readyErrors.length>0} onClick={()=>accept('accepted_analysis_ready')}>Accept — analysis ready</button></div></div>}
 <div className="sticky bottom-0 flex flex-wrap gap-3 border-t border-[#30363d] bg-[#0d1117] p-3"><button className={button} onClick={()=>perform(async()=>{await save();setMessage('Draft saved. You can resume it from NewsIngestion.');})}>{busy?'Saving…':'Save draft'}</button>{step>0&&<button className={button} onClick={()=>setStep(step-1)}>Previous</button>}{step<4&&<button className={button} onClick={()=>setStep(step+1)}>Next</button>}<span aria-live="polite">{dirty?'Unsaved changes':''}</span></div>
 </fieldset>
 {showGuide&&<ReviewGuide key={step} step={step} open={guideOpen} onToggle={()=>setGuideOpen(!guideOpen)}/>}
 </div>}
 {!!data.versions.length&&<section className="space-y-4 border-t border-[#30363d] pt-5"><h2 className="text-xl">Accepted version history</h2><label>Version<select className={box} value={selectedVersion?.id??''} onChange={e=>setVersionId(e.target.value)}>{data.versions.map(v=><option key={v.id} value={v.id}>Version {v.version_no} — {v.outcome.replaceAll('_',' ')} — {v.accepted_at}</option>)}</select></label>{selectedVersion&&<><p>Accepted: {selectedVersion.accepted_at} · Published: {selectedVersion.published_at??'unknown'} · Ingested: {selectedVersion.ingested_at??'unknown'}</p><ReviewSummary document={selectedVersion.snapshot} entities={Object.fromEntries(data.entities.map(e=>[e.id,e.name]))}/><details><summary>Stored scoring snapshots</summary>{data.scores.filter(s=>s.version_id===selectedVersion.id).map(s=><pre key={s.id} className="overflow-auto text-xs">{JSON.stringify({input:s.input,output:s.output},null,2)}</pre>)}</details></>}
 {!editing&&data.canReview&&<button className={button} onClick={()=>{setDoc(structuredClone(data.versions[0].snapshot));setDraft(null);setDirty(true);setEditing(true);setStep(0);}}>Create revised draft from latest version</button>}
 <h2 className="text-xl">Daily observations</h2><p className="text-sm">Observations do not change acceptance-time forecasts. Price movements are not proof of causality. No market data is generated automatically.</p>{!data.observations.length&&<p>No daily observations yet.</p>}{data.observations.map(o=><details key={o.id} className="rounded border border-[#30363d] p-3"><summary>{o.analysis_date} · {data.entities.find(e=>e.id===o.entity_id)?.name} · version {data.versions.find(v=>v.id===o.version_id)?.version_no} · {o.fields.outcome}</summary>{Object.entries(o.fields).map(([key,value])=><p className="whitespace-pre-wrap" key={key}><strong>{key.replaceAll('_',' ')}:</strong> {String(value??'unknown')}</p>)}</details>)}
 {data.canReview&&selectedVersion&&<details><summary>Add manual observation for selected version {selectedVersion.version_no}</summary><fieldset disabled={busy}><FieldsForm spec={observationFields} values={observation} onChange={values=>{setObservation(values);setObservationDirty(true);}} options={{entity_id:entityOptions.filter(e=>selectedVersion.snapshot.mappings.some(m=>m.fields.entity_id===e.value)),security_id:data.securities.filter(s=>s.entity_id===observation.entity_id).map(s=>({value:s.id,label:s.symbol}))}}/><button className={button} onClick={()=>perform(async()=>{await request('observe',{version_id:selectedVersion.id,fields:observation});await refresh();setObservation({mode:'carried_forward',outcome:'pending'});setObservationDirty(false);setMessage('Observation added; accepted history is unchanged.');})}>Save observation</button></fieldset></details>}
 </section>}
 <details><summary>Audit history</summary>{data.audit.map(a=><p key={a.id}>{a.created_at} · {a.action} · {a.actor_id}</p>)}</details>
 </section>;
}
