import Link from 'next/link';
import type {ReviewDocument,Values} from '@/lib/reviews/model';
import {safeUrl} from '@/lib/reviews/model';
function Details({values}:{values:Values}){return <dl className="grid gap-2 sm:grid-cols-2">{Object.entries(values).filter(([,v])=>v!==null&&v!=='').map(([k,v])=><div key={k}><dt className="text-xs text-[#9aa7b4]">{k.replaceAll('_',' ')}</dt><dd className="whitespace-pre-wrap break-words">{String(v)}</dd></div>)}</dl>;}
export default function ReviewSummary({document,entities={}}:{document:ReviewDocument;entities?:Record<string,string>}){return <div className="space-y-4 text-sm">
 <h3 className="text-lg font-semibold">{document.verification.headline}</h3><p>Verification: <strong>{String(document.verification.verification_status).replaceAll('_',' ')}</strong>. Acceptance does not confirm a claim.</p><p className="whitespace-pre-wrap">{document.verification.summary}</p>
 <details><summary>Verification and acceptance reasoning</summary><Details values={document.verification}/></details>
 <div><h4 className="font-semibold">Supporting evidence</h4>{document.evidence.map(e=><div key={e.id} className="my-2">{typeof e.fields.url==='string'&&safeUrl(e.fields.url)?<a className="text-[#58a6ff] underline" target="_blank" rel="noopener noreferrer" href={e.fields.url}>{e.fields.label}</a>:<span>{e.fields.label}</span>}<span> · {e.fields.classification} · added {e.added_at}</span>{e.fields.document_ref&&<p>{e.fields.document_ref}</p>}{e.fields.excerpt&&<blockquote className="border-l-2 pl-3 whitespace-pre-wrap">{e.fields.excerpt}</blockquote>}</div>)}</div>
 {document.mappings.map(m=><details key={m.id} open className="rounded border border-[#30363d] p-3"><summary className="font-semibold">{entities[String(m.fields.entity_id)]??m.fields.entity_id??'Mapping pending'} · {m.fields.exposure} · {m.impact.direction??'unknown'} / {m.impact.magnitude??'unknown'} magnitude</summary><p className="my-2 whitespace-pre-wrap">{m.impact.rationale}</p><p>{m.chain.join(' → ')}</p><p>Mapping confidence: {m.fields.mapping_confidence??'unknown'} · Impact confidence: {m.impact.impact_confidence??'unknown'} (uncalibrated heuristics)</p><details><summary>Full mapping, metrics, assumptions and advanced analysis</summary><Details values={m.fields}/><Details values={m.impact}/>{m.metrics.map((metric,i)=><Details key={i} values={metric}/>)}<Details values={m.advanced}/></details>{m.horizons.map((h,i)=><div className="mt-3 border-t border-[#30363d] pt-2" key={i}><h4>{h.horizon} · {h.direction} · {h.magnitude}</h4><Details values={h}/></div>)}</details>)}
 {!document.mappings.length&&<p>Entity mapping pending.</p>}
 </div>;}
export function ReviewLink({article}:{article:string}){return <Link className="text-[#58a6ff] underline" href={`/app/news-review/${encodeURIComponent(article)}`}>Full review, version history and observations</Link>;}
