-- Missing historical base tables. IF NOT EXISTS preserves existing deployments.
CREATE TABLE IF NOT EXISTS public.entities (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL,
 ticker text, sector text, aliases text[], created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.sources (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL,
 credibility double precision NOT NULL DEFAULT 0.5, created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_id uuid REFERENCES public.entities(id) ON DELETE SET NULL,
 title text NOT NULL, event_type text NOT NULL, occurred_at timestamptz NOT NULL,
 detected_at timestamptz DEFAULT now(), impact_score double precision, impact_direction text,
 confidence double precision, significance text, materiality text, summary text, rationale text,
 affected_metrics jsonb, raw jsonb, source_id uuid REFERENCES public.sources(id) ON DELETE SET NULL, source_url text
);
CREATE TABLE IF NOT EXISTS public.impact_records (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company text NOT NULL, security text, sector text,
 event_type text, event_status text, direction text, horizon text, materiality text,
 confidence double precision, summary text, evidence_url text, created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.event_links (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_event uuid REFERENCES public.events(id) ON DELETE SET NULL,
 target_event uuid REFERENCES public.events(id) ON DELETE SET NULL, relation text, created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.backlog_items (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, description text,
 priority text, status text, created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.cicd_test (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.tasks (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text NOT NULL, description text,
 completed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
